# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Simple-Month
version:      0.02
version_from: lib/Date/Simple/Month.pm
installdirs:  site
requires:
    Date::Range:                   0
    Date::Simple:                  0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
